package com.campusskills.shared.constants;

public enum DisputeReason {
    PAYMENT_EVASION,
    PREMATURE_COMPLETION,
    PARTIAL_SESSION,
    NO_SHOW,
    FALSE_NO_SHOW,
    SWAP_GHOSTING,
    SWAP_QUALITY_IMBALANCE,
    QUALITY_ISSUE,
    MISREPRESENTATION,
    CONDUCT_VIOLATION,
    CHAT_HARASSMENT,
    AVAILABILITY_ABUSE,
    RETALIATORY_REVIEW,
    OTHER
}
