package com.campusskills.modules.notifications.models;

public enum NotificationType {
    CHAT_REQUEST_RECEIVED,
    CHAT_REQUEST_ACCEPTED,
    
    EXCHANGE_REQUEST_RECEIVED,
    EXCHANGE_REQUEST_ACCEPTED,
    EXCHANGE_REQUEST_REJECTED,
    
    SESSION_PROPOSED,
    SESSION_ACCEPTED,
    SESSION_REJECTED,
    SESSION_CANCELLED,
    
    SESSION_COMPLETION_PENDING,
    SESSION_COMPLETED,
    
    NEW_CHAT_ACTIVITY,
    
    ADMIN_NEW_STUDENT,
    ADMIN_SESSION_BOOKED,
    ADMIN_PAYMENT_RECEIVED,
    ADMIN_DISPUTE_RAISED,
    ADMIN_DISPUTE_RESOLVED,
    
    PAYMENT_RECEIVED,
    NEW_MESSAGE,
    SKILL_VERIFICATION_PASSED,
    SKILL_VERIFICATION_FAILED
}
