package com.campusskills.modules.notifications.models;

public enum NotificationType {
    CHAT_REQUEST_RECEIVED,
    CHAT_REQUEST_ACCEPTED,
    
    EXCHANGE_REQUEST_RECEIVED,
    EXCHANGE_REQUEST_ACCEPTED,
    EXCHANGE_REQUEST_REJECTED,
    
    SESSION_PROPOSED,
    SESSION_ACCEPTED,
    SESSION_REJECTED,
    SESSION_CANCELLED,
    
    SESSION_COMPLETION_PENDING,
    SESSION_COMPLETED,
    
    NEW_CHAT_ACTIVITY
}
