package com.campusskills.modules.listings.handlers;

import com.campusskills.modules.listings.models.Listing;
import com.campusskills.modules.listings.services.ListingService;
import com.campusskills.shared.models.SkillProfile;
import com.campusskills.web.response.ApiResponse;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.RoutingContext;

import java.util.Arrays;
import java.util.List;

public class ListingHandler {

    private final ListingService listingService;
    private static final List<String> VALID_DAYS = Arrays.asList("MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY");

    public ListingHandler(ListingService listingService) {
        this.listingService = listingService;
    }

    public void createListing(RoutingContext ctx) {
        try {
            String authenticatedUserId = ctx.get("authenticatedUserId");
            if (authenticatedUserId == null) {
                ApiResponse.sendError(ctx, 401, "Unauthorized");
                return;
            }

            JsonObject body = ctx.body().asJsonObject();
            if (body == null) {
                ApiResponse.sendError(ctx, 400, "Missing request body");
                return;
            }

            Listing listing;
            try {
                listing = body.mapTo(Listing.class);
            } catch (IllegalArgumentException e) {
                ApiResponse.badRequest(ctx, "Invalid payload or enum value");
                return;
            }

            // 1. Required Text Fields
            if (listing.getTitle() == null || listing.getTitle().trim().isEmpty()) {
                ApiResponse.badRequest(ctx, "Title is required");
                return;
            }
            if (listing.getDescription() == null || listing.getDescription().trim().isEmpty()) {
                ApiResponse.badRequest(ctx, "Description is required");
                return;
            }
            if (listing.getCategory() == null || listing.getCategory().trim().isEmpty()) {
                ApiResponse.badRequest(ctx, "Category is required");
                return;
            }

            // 2. Skills Validation
            if (listing.getSkills() == null || listing.getSkills().isEmpty()) {
                ApiResponse.badRequest(ctx, "At least one skill is required");
                return;
            }
            for (SkillProfile skill : listing.getSkills()) {
                if (skill.getName() == null || skill.getName().trim().isEmpty()) {
                    ApiResponse.badRequest(ctx, "Skill name is required and cannot be blank");
                    return;
                }
                if (skill.getLevel() == null) {
                    ApiResponse.badRequest(ctx, "Skill level is required");
                    return;
                }
            }

            // 3. Available Slots Validation
            if (listing.getAvailableSlots() == null || listing.getAvailableSlots().isEmpty()) {
                ApiResponse.badRequest(ctx, "At least one available slot is required");
                return;
            }
            for (com.campusskills.modules.listings.models.ListingSlot slot : listing.getAvailableSlots()) {
                if (slot.getDayOfWeek() == null) {
                    ApiResponse.badRequest(ctx, "Slot day of week is required");
                    return;
                }
                if (slot.getStartTime() == null || slot.getStartTime().trim().isEmpty()) {
                    ApiResponse.badRequest(ctx, "Slot start time is required");
                    return;
                }
                if (slot.getDurationMinutes() == null || slot.getDurationMinutes() <= 0) {
                    ApiResponse.badRequest(ctx, "Slot duration must be greater than 0");
                    return;
                }
                if (slot.getId() == null || slot.getId().trim().isEmpty()) {
                    // ID should be auto-generated by the constructor, but just in case frontend overrides with null
                    slot.setId(java.util.UUID.randomUUID().toString());
                }
            }

            // 4. Enums Null Checks (Since they could be missing from payload)
            if (listing.getSessionType() == null) {
                ApiResponse.badRequest(ctx, "SessionType is required");
                return;
            }
            if (listing.getAvailability() == null) {
                ApiResponse.badRequest(ctx, "Availability is required");
                return;
            }

            // ENFORCE authenticated user identity! Ignore any teacherId passed from frontend
            listing.setTeacherId(authenticatedUserId);

            listingService.createListing(listing)
                .onSuccess(listingId -> {
                    JsonObject response = new JsonObject().put("id", listingId);
                    ApiResponse.created(ctx, response);
                })
                .onFailure(err -> ApiResponse.sendError(ctx, 500, "Failed to create listing"));

        } catch (Exception e) {
            e.printStackTrace();
            ApiResponse.sendError(ctx, 400, "Invalid request payload");
        }
    }

    public void getAllListings(RoutingContext ctx) {
        String q = ctx.request().getParam("q");
        List<String> topics = ctx.queryParam("topics");
        List<String> paymentTypes = ctx.queryParam("payment_types");
        List<String> modes = ctx.queryParam("modes");
        String sort = ctx.request().getParam("sort");
        
        int page = 1;
        int limit = 20;
        try {
            if (ctx.request().getParam("page") != null) page = Integer.parseInt(ctx.request().getParam("page"));
            if (ctx.request().getParam("limit") != null) limit = Integer.parseInt(ctx.request().getParam("limit"));
        } catch (NumberFormatException ignored) {}

        JsonObject filters = new JsonObject();
        if (q != null && !q.trim().isEmpty()) filters.put("q", q.trim());
        if (topics != null && !topics.isEmpty()) filters.put("topics", new io.vertx.core.json.JsonArray(topics));
        if (paymentTypes != null && !paymentTypes.isEmpty()) filters.put("payment_types", new io.vertx.core.json.JsonArray(paymentTypes));
        if (modes != null && !modes.isEmpty()) filters.put("modes", new io.vertx.core.json.JsonArray(modes));
        if (sort != null && !sort.trim().isEmpty()) filters.put("sort", sort.trim());

        listingService.searchListings(filters, page, limit)
            .onSuccess(result -> {
                ApiResponse.ok(ctx, result);
            })
            .onFailure(err -> {
                err.printStackTrace();
                ApiResponse.internalError(ctx, "Failed to retrieve listings");
            });
    }

    public void getListingById(RoutingContext ctx) {
        String id = ctx.pathParam("id");
        if (id == null || id.trim().isEmpty()) {
            ApiResponse.badRequest(ctx, "Listing ID is required");
            return;
        }

        listingService.getListingById(id)
            .onSuccess(listing -> ApiResponse.ok(ctx, JsonObject.mapFrom(listing)))
            .onFailure(err -> {
                if ("NOT_FOUND".equals(err.getMessage())) {
                    ApiResponse.notFound(ctx, "Listing not found");
                } else {
                    err.printStackTrace();
                    ApiResponse.internalError(ctx, "Failed to retrieve listing");
                }
            });
    }
}
