/**
 * Builds the complete questions.json by:
 * 1. Reading existing questions
 * 2. Adding 10 new questions per existing skill (→ 20 each)
 * 3. Adding 10 questions per missing skill (→ minimum viable bank)
 *
 * Run: node build_questions.js > questions_new.json
 * Then replace questions.json with questions_new.json
 */

const fs = require('fs');
const path = require('path');

// Compact question format: [skill, question, optA, optB, optC, optD, correctIdx, difficulty, explanation]
const NEW = [
  // ===== PYTHON (expand 10→20) =====
  ["Python","What does the 'pass' statement do in Python?","Acts as a placeholder no-op","Terminates the function","Throws an exception","Continues to next iteration",0,"easy","pass is a null operation used when syntax requires a statement but no action is needed."],
  ["Python","How do you handle multiple exceptions in a single except block?","except (TypeError, ValueError) as e:","except TypeError, ValueError:","catch TypeError, ValueError:","except [TypeError, ValueError]:",0,"medium","Parentheses group exception types in a single except clause, available since Python 2.6/3.0."],
  ["Python","What is the output of bool([])?","False","True","None","TypeError",0,"medium","Empty sequences and collections (lists, dicts, strings, sets, tuples) evaluate to False in boolean context."],
  ["Python","Which method adds elements from an iterable to the end of a list?","extend()","append()","insert()","concat()",0,"medium","extend() iterates over the argument and adds each element to the list, unlike append() which adds the argument as a single element."],
  ["Python","What is a generator expression?","A memory-efficient way to create iterators using () syntax","A function that generates random numbers","A list comprehension with yield","A class that implements __next__",0,"hard","Generator expressions use (x for x in iterable) syntax and produce values lazily without storing the entire sequence in memory."],
  ["Python","What does the 'with' statement provide in Python?","Context manager for resource cleanup","Value assignment","Loop iteration","Exception raising",0,"medium","The with statement ensures that context manager's __enter__ and __exit__ methods are called, guaranteeing proper resource management."],
  ["Python","What does '===' do in Python?","This operator does not exist","Checks both value and type","Checks reference equality","Checks value equality",0,"easy","Python uses 'is' for identity comparison and '==' for value equality. '===' is not a Python operator."],
  ["Python","What is the purpose of __init__?","Constructor called when an instance is created","Destructor called when an object is deleted","String representation method","Comparison method",0,"easy","__init__ initializes a newly created instance. It's not technically the constructor (__new__ is), but it sets up the initial state."],
  ["Python","Which module provides support for regular expressions?","re","regex","regexp","pcre",0,"easy","The 're' module provides Perl-like regular expression pattern matching operations in Python."],
  ["Python","What does zip() do in Python?","Pairs elements from multiple iterables into tuples","Compresses files","Zips archive files","Encodes strings",0,"medium","zip() aggregates elements from multiple iterables, stopping when the shortest input iterable is exhausted."],

  // ===== JAVA (expand 10→20) =====
  ["Java","What is the difference between abstract class and interface?","Abstract classes can have implemented methods; interfaces traditionally only declare methods (pre-Java 8)","Interfaces can have constructors; abstract classes cannot","Abstract classes support multiple inheritance; interfaces don't","There is no difference",0,"medium","Abstract classes can have state and implemented methods. Since Java 8, interfaces can have default and static methods but cannot hold state."],
  ["Java","Which annotation marks a method that overrides a superclass method?","@Override","@Overwrite","@Inherit","@OverrideMethod",0,"easy","@Override is a compile-time annotation that informs the compiler the method intends to override a superclass method, catching errors if the signature doesn't match."],
  ["Java","What is the purpose of the finalize() method?","Called by the garbage collector before reclaiming an object","Initializes an object","Terminates the program","Creates a final object reference",0,"medium","finalize() is deprecated since Java 9; it was called before garbage collection but has unpredictable behavior. Use try-with-resources or Cleaner instead."],
  ["Java","Which class is the root of the Java class hierarchy?","Object","Class","System","Root",0,"easy","Every class in Java inherits from java.lang.Object either directly or indirectly through a chain of superclasses."],
  ["Java","What is method overloading in Java?","Multiple methods with same name but different parameters","Multiple methods with different names","Overriding a superclass method","Creating a method with the same signature in different classes",0,"easy","Overloading allows a class to have multiple methods with the same name but different parameter lists (compile-time polymorphism)."],
  ["Java","Which collection maintains insertion order?","LinkedHashMap","HashMap","TreeMap","Hashtable",0,"medium","LinkedHashMap maintains a doubly-linked list of entries, preserving iteration order (insertion-order by default, or access-order)."],
  ["Java","What does the 'synchronized' keyword ensure?","Only one thread can execute the method or block at a time","The method runs faster","Variables are automatically saved to disk","The class cannot be inherited",0,"medium","synchronized prevents thread interference and memory consistency errors by requiring a thread to acquire a lock before executing the guarded code."],
  ["Java","What is an enum in Java?","A special type that defines a set of named constants","A method that enumerates array elements","A class that counts iterations","A variable that increments automatically",0,"easy","Enums (enum keyword) are classes that have a fixed set of constants. They can have fields, methods, and constructors."],
  ["Java","What is the Java Memory Model?","A specification defining how threads interact through memory","A physical memory layout diagram","A garbage collection algorithm","A memory allocation strategy",0,"hard","The JMM defines the rules for how and when changes made by one thread become visible to others, covering volatile, synchronized, and happens-before relationships."],
  ["Java","Which operator performs bitwise AND in Java?","&","&&","|","||",0,"medium","The single & operator performs bitwise AND on integer types and acts as non-short-circuit AND on booleans."],

  // ===== JAVASCRIPT (expand 10→20) =====
  ["JavaScript","What is NaN in JavaScript?","Not-a-Number, a special value when math operations fail","Null and Null","A Number wrapper object","A syntax error indicator",0,"medium","NaN is a property of the global object, representing an unrepresentable or invalid number. typeof NaN returns 'number'."],
  ["JavaScript","What is 'use strict' in JavaScript?","Enforces stricter parsing and error handling","Prevents variable declaration","Enables type checking","Optimizes code execution",0,"medium","Strict mode ('use strict') catches common coding mistakes like undeclared variables and throws more exceptions, making JavaScript more secure."],
  ["JavaScript","What is a Promise.all() used for?","Waiting for all promises in an iterable to resolve","Resolving the first promise that settles","Creating multiple promises","Cancelling all pending promises",0,"medium","Promise.all() takes an iterable of promises and returns a single promise that resolves when all input promises resolve, or rejects if any rejects."],
  ["JavaScript","What does JSON.parse() do?","Converts a JSON string to a JavaScript object","Converts an object to a JSON string","Parses a URL","Validates JSON syntax",0,"easy","JSON.parse() parses a JSON-formatted string and constructs the JavaScript value or object described by the string."],
  ["JavaScript","What is the 'this' value inside a regular function called without context?","The global object (window in browsers)","undefined","null","The function itself",0,"medium","In non-strict mode, 'this' defaults to the global object. In strict mode, it's undefined."],
  ["JavaScript","What does the 'new' keyword do?","Creates an instance of a constructor function","Declares a new variable","Allocates memory for a primitive","Creates a new scope",0,"medium","new creates a new object, sets its prototype to the constructor's prototype, binds 'this' to the new object, and returns it implicitly."],
  ["JavaScript","What method adds one or more elements to the end of an array?","push()","pop()","unshift()","append()",0,"easy","push() appends elements to the end of an array and returns the new length."],
  ["JavaScript","What is the difference between == and ===?","=== checks both value and type; == checks value with type coercion","== checks both value and type; === only checks value","They are identical","=== is faster than ==",0,"easy","The loose equality (==) coerces operands to the same type before comparing; strict equality (===) returns false for different types."],
  ["JavaScript","What does the 'bind()' method do?","Creates a new function with a fixed 'this' value","Attaches an event handler","Links two variables together","Merges objects",0,"medium","bind() returns a new function with the specified 'this' value and optional preset arguments (partial application)."],
  ["JavaScript","What is a Set in JavaScript?","A collection of unique values of any type","A sorted array","A key-value store","A type of function",0,"easy","Set objects store unique values. Each value can only occur once; duplicate values are automatically removed."],

  // ===== C++ (expand 10→20) =====
  ["C++","What is the correct header for std::string?","<string>","<cstring>","<str>","<string.h>",0,"easy","The <string> header provides the std::string class. <cstring> and <string.h> provide C-style string functions."],
  ["C++","What does 'auto' keyword do in modern C++?","Deduces variable type from its initializer","Creates automatic storage duration","Deletes a variable","Auto-increments a variable",0,"medium","Since C++11, auto deduces the type from the initializer expression, enabling simpler code and reducing type verbosity."],
  ["C++","Which type of inheritance creates the most derived class from multiple base classes?","Multiple inheritance","Single inheritance","Hierarchical inheritance","Hybrid inheritance",0,"easy","Multiple inheritance allows a class to inherit from more than one base class. It can introduce the diamond problem."],
  ["C++","What does 'nullptr' represent?","A null pointer value","A null integer","A null character","A null reference",0,"easy","nullptr is the null pointer literal introduced in C++11. It has type std::nullptr_t and implicitly converts to any pointer type."],
  ["C++","What is a template in C++?","A blueprint for generating generic types or functions","A pre-written code snippet","A macro for code generation","A design pattern",0,"medium","Templates enable generic programming by allowing functions and classes to operate on types as parameters, resolved at compile time."],
  ["C++","What is the difference between struct and class?","Default access: struct is public, class is private","structs cannot have methods","classes cannot have data members","They are identical in all aspects",0,"medium","In C++, the only difference is that struct members default to public access and class members default to private access."],
  ["C++","What does 'std::move' do?","Casts to an rvalue reference, enabling move semantics","Physically moves an object in memory","Copies an object","Deletes an object",0,"hard","std::move is a cast that converts its argument to an rvalue reference, allowing the compiler to select move constructors/assignment operators."],
  ["C++","Which header provides std::array?","<array>","<vector>","<list>","<tuple>",0,"easy","std::array is a fixed-size array container provided by the <array> header, available since C++11."],
  ["C++","What is the RAII principle?","Resource Allocation Is Initialization","Random Access Iterator Implementation","Rapid Application Integration Interface","Return Address Is Invalid",0,"hard","RAII binds resource lifetime to object lifetime: resources are acquired during construction and released during destruction, preventing leaks."],
  ["C++","What is a friend function?","A non-member function granted access to private/protected members","A function called on friend objects","A function that creates friendships","A function defined inside a friend class",0,"medium","A friend function is a non-member function (or class) that has access to the private and protected members of the class that declares it as a friend."],

  // ===== C (expand 10→20) =====
  ["C","What does the 'static' keyword do to a local variable?","Preserves its value between function calls","Makes it global","Initializes it to zero once","Prevents modification",0,"medium","Static local variables retain their value across calls and have lifetime of the program but scope limited to the function."],
  ["C","Which function is used to dynamically allocate memory for multiple elements?","calloc()","alloc()","realloc()","malloc()",0,"easy","calloc() allocates memory for an array of elements, initializing all bytes to zero, unlike malloc() which does not initialize."],
  ["C","What is a function pointer in C?","A variable that stores the address of a function","A pointer to a struct","A pointer to void","A function that returns a pointer",0,"medium","Function pointers store the address of executable code, enabling callbacks and dynamic dispatch in C."],
  ["C","What is the result of '5 & 3' (bitwise AND)?","1","5","3","7",0,"easy","Binary AND: 5 = 101, 3 = 011, result = 001 = 1."],
  ["C","How do you define a constant using the preprocessor?","#define PI 3.14","const PI = 3.14","int PI = 3.14","macro PI = 3.14",0,"easy","#define preprocessor directive replaces all occurrences of PI with 3.14 before compilation. No type checking, unlike const."],
  ["C","What is the purpose of 'typedef'?","Creating an alias for an existing type","Defining a new data type","Type casting","Defining a function",0,"easy","typedef creates a shorthand or alias for an existing type, improving code readability and portability."],
  ["C","What does the 'extern' keyword specify?","A variable or function defined in another file","An external device connection","An extended precision type","An exception handler",0,"medium","extern tells the compiler that a variable or function is defined elsewhere (typically in another source file), preventing multiple definition errors."],
  ["C","What is a null-terminated string in C?","A character array ending with '\\0'","A string with no characters","A string pointer set to NULL","A string with zero length",0,"easy","C strings are arrays of char ending with a null character ('\\0', ASCII 0), marking the string's end."],
  ["C","Which function reads a line from stdin?","fgets()","scanf()","gets()","getline()",0,"medium","fgets() reads a line from a stream including the newline, bounded by buffer size. gets() is dangerous (no bounds checking) and removed from C11."],
  ["C","What does the 'volatile' qualifier indicate?","The variable may change unexpectedly, preventing compiler optimization","The variable is volatile (explosive)","The variable cannot be changed","The variable is stored in volatile memory",0,"hard","volatile tells the compiler the variable can change at any time (e.g., by hardware or another thread), forcing reads/writes to occur in memory."],

  // ===== C# (expand 10→20) =====
  ["C#","What is a property in C#?","A member that provides a flexible mechanism to read/write private fields","A class variable","A method that returns a value","A field declaration",0,"medium","Properties combine fields and methods, allowing computed or validated access with get and set accessors."],
  ["C#","What does 'var' keyword mean in C#?","Implicitly typed local variable","Variant type","Variable reference","Volatile auto-release",0,"easy","var tells the compiler to infer the type from the initialization expression. The type is fixed at compile time."],
  ["C#","Which keyword exits a loop immediately?","break","continue","return","exit",0,"easy","break terminates the nearest enclosing loop or switch statement immediately."],
  ["C#","What is LINQ?","Language Integrated Query for querying data sources","A web framework","A database engine","A logging library",0,"medium","LINQ provides compile-time checked query capabilities against collections, databases, and XML using SQL-like syntax or method chaining."],
  ["C#","What is the 'using' statement used for?","Ensuring proper disposal of IDisposable resources","Importing namespaces","Declaring global variables","Creating object aliases",0,"medium","The using statement ensures Dispose() is called even if an exception occurs, providing deterministic cleanup for unmanaged resources."],
  ["C#","What is boxing in C#?","Converting a value type to a reference type (object)","Converting a reference type to a value type","Wrapping an exception","Encapsulating a method",0,"medium","Boxing wraps a value type (like int) inside an object on the heap. Unboxing extracts it back. Both have performance costs."],
  ["C#","What does 'params' keyword allow?","Variable number of arguments in a method","Optional parameters","Named arguments","Ref parameters",0,"medium","The params keyword lets a method accept a variable number of arguments as an array parameter, which must be the last parameter."],
  ["C#","Which collection type provides key-value storage?","Dictionary","List","Array","HashSet",0,"easy","Dictionary<TKey,TValue> stores key-value pairs for fast lookups by key."],
  ["C#","What is an extension method?","A static method that appears to extend a type without inheritance","A method that extends a base class","A method that can be called on any type","A method that extends enum values",0,"medium","Extension methods are static methods in static classes, called using instance syntax. The first parameter with 'this' specifies the type being extended."],
  ["C#","What is the purpose of the 'yield' keyword?","Creating iterator methods with deferred execution","Pausing thread execution","Returning early from a method","Yielding processor time",0,"hard","yield return returns each element one at a time in an iterator, and yield break terminates iteration. The state machine is generated by the compiler."],

  // ===== TYPESCRIPT (expand 10→20) =====
  ["TypeScript","What are union types?","A type that can be one of several specified types","A type that merges multiple interfaces","A type that combines arrays","A type with common properties",0,"easy","Union types (string | number) allow a value to be any of the listed types."],
  ["TypeScript","What does 'keyof' operator do?","Returns a union of known public property names of a type","Returns the key type of a dictionary","Extracts the key from an object","Returns the type of object keys",0,"hard","keyof T yields a union type of all public property keys of T, commonly used for type-safe accessors."],
  ["TypeScript","What is a type guard?","An expression that narrows the type within a conditional block","A function that validates data","A middleware for type checking","A decorator that enforces types",0,"medium","Type guards (typeof, instanceof, or custom functions returning x is Type) allow TypeScript to narrow union types within conditional blocks."],
  ["TypeScript","How do you create an intersection type?","type A = B & C","type A = B | C","type A = B extends C","type A = [B, C]",0,"medium","Intersection types (&) combine multiple types into one, requiring all properties of each constituent type."],
  ["TypeScript","What does 'as const' do?","Marks the expression as deeply read-only with literal types","Casts to constant type","Makes a variable constant","Prevents type widening",0,"hard","as const infers the narrowest type (literal values instead of widened types) and marks all properties as readonly."],
  ["TypeScript","What is the 'never' type?","A type representing values that never occur","A type that's undefined","A type for unreachable code","A type that represents null",0,"medium","never is the bottom type, representing values that never occur (thrown exceptions, infinite loops, exhaustive conditional branches)."],
  ["TypeScript","Which compiler flag enables strict null checking?","strictNullChecks","noNullChecks","nullCheck","enableNullSafety",0,"easy","When strictNullChecks is true, null and undefined have their own types, and you must handle them explicitly."],
  ["TypeScript","What is a mapped type?","A type created by transforming properties of an existing type","A type that maps keys to values","A type that maps function arguments","A type generated by the compiler",0,"medium","Mapped types use syntax like { [K in keyof T]: T[K] } to create new types based on existing ones (e.g., Partial<T>, Readonly<T>)."],
  ["TypeScript","What does 'declare' keyword do?","Tells TypeScript a variable exists elsewhere without implementation","Declares a new variable","Declares a function body","Declares a class constructor",0,"medium","declare is used in .d.ts files or ambient declarations to describe JavaScript code to TypeScript without providing implementation."],
  ["TypeScript","What is the difference between interface and type?","Interfaces can be extended/merged; type aliases cannot be reopened","type can describe union/intersection; interface can use extends","Both A and B","There is no difference",2,"medium","Interfaces support declaration merging and extends. Types can represent unions, intersections, and primitives. Prefer interface for object shapes, type for complex types."],

  // ===== NODE.JS (expand 10→20) =====
  ["Node.js","What is the 'path' module used for?","Working with file and directory paths","Configuring server routes","Setting environment paths","Managing module resolution",0,"easy","path provides utilities for handling and transforming file paths in a cross-platform manner."],
  ["Node.js","What does 'process.nextTick()' do?","Schedules a callback to run before the next event loop phase","Creates a new process","Starts a timer","Emits a process event",0,"medium","nextTick() schedules a callback to run after the current operation completes but before the event loop continues, giving higher priority than setTimeout."],
  ["Node.js","How do you read a file asynchronously in Node.js?","fs.readFile()","fs.readFileSync()","fs.open().read()","fs.read()",0,"easy","fs.readFile() reads the entire file into memory asynchronously, calling the callback with (err, data)."],
  ["Node.js","What is middleware in Express?","Functions that process requests in the middleware stack","A database layer","A security protocol","A template engine",0,"easy","Express middleware functions have access to req, res, and next, allowing them to modify request/response objects, end requests, or call the next middleware."],
  ["Node.js","What is 'npm' primarily used for?","Managing Node.js package dependencies","Running Node.js applications","Compiling TypeScript","Monitoring server performance",0,"easy","npm (Node Package Manager) downloads and manages JavaScript packages, including versioning and dependency resolution."],
  ["Node.js","What is the difference between process.nextTick() and setImmediate()?","nextTick runs before setImmediate in the event loop","setImmediate runs before nextTick","They are identical","Both are deprecated",0,"medium","nextTick callbacks execute after the current operation, before I/O. setImmediate callbacks run in the check phase, after I/O callbacks."],
  ["Node.js","What is the buffer class used for?","Handling binary data directly","Buffering HTTP responses","Caching files","Storing string data",0,"medium","Buffer provides a way to work with raw binary data in Node.js, allocated outside the V8 heap."],
  ["Node.js","Which method creates a readable stream from a file?","fs.createReadStream()","fs.readStream()","fs.openStream()","fs.readFile()",0,"easy","fs.createReadStream() returns a Readable stream that emits 'data' events as chunks are read from the file."],
  ["Node.js","What is a package.json file?","Metadata about the Node.js project including dependencies","A JSON configuration for the Node.js runtime","A build script for the application","A test configuration file",0,"easy","package.json contains project metadata, scripts, dependencies, and version information required for npm to manage the project."],
  ["Node.js","What is an event emitter in Node.js?","A pattern for handling asynchronous events using listeners","A device that emits signals","A function that fires automatically","A DOM event handler",0,"medium","EventEmitter is a core Node.js class that supports emitting named events and registering listener functions, forming the basis of many Node.js APIs."],

  // ===== EXPRESS.JS (expand 10→20) =====
  ["Express.js","What is the req object in Express?","Represents the HTTP request with properties like params, query, body","The response object sent to the client","The middleware queue","The server configuration",0,"easy","req (request) contains information about the incoming HTTP request including URL parameters, query strings, headers, and body."],
  ["Express.js","How do you set a response status code?","res.status(404).send('Not Found')","res.statusCode = 404","res.sendStatus(404)","All of the above",3,"easy","Express provides multiple ways to set status codes: res.status(), res.sendStatus(), and res.status().send() are all valid."],
  ["Express.js","What is a router in Express?","A mini-application capable of performing middleware and routing functions","A device that forwards network traffic","A URL parser","A database connector",0,"medium","express.Router() creates modular route handlers that can be mounted at specific paths, organizing routes across multiple files."],
  ["Express.js","How do you serve static files in Express?","express.static('public')","app.serve('public')","app.static('public')","express.serve('public')",0,"easy","express.static() middleware serves static files (HTML, CSS, images) from a specified directory."],
  ["Express.js","What does 'app.use()' do?","Mounts middleware at a specified path","Starts the server","Defines a GET route","Creates a new Express app",0,"easy","app.use() mounts middleware functions at a path. Without a path, the middleware runs on every request."],
  ["Express.js","How do you access URL query parameters?","req.query","req.params","req.body","req.url",0,"medium","req.query contains parsed query string parameters (e.g., ?name=John). req.params holds route parameters (e.g., /users/:id)."],
  ["Express.js","What is error-handling middleware?","Middleware with four parameters (err, req, res, next)","Middleware that never errors","The default middleware","Middleware at the start of the stack",0,"medium","Error-handling middleware has four parameters and is defined at the end of the middleware stack to catch errors from preceding middleware."],
  ["Express.js","How do you redirect a client to another URL?","res.redirect('/new-path')","res.redirect(301, '/new-path')","Both A and B","res.sendRedirect('/new-path')",2,"medium","res.redirect() defaults to 302. A status code can be passed as the first argument for permanent (301) redirects."],
  ["Express.js","What does 'app.route()' enable?","Chainable route handlers for a single path","Multiple routes on different ports","Router-level middleware","Static file serving",0,"medium","app.route('/path').get(...).post(...).put(...) allows chaining HTTP method handlers for the same route, keeping definitions organized."],
  ["Express.js","Which method sends a file as an attachment for download?","res.download()","res.sendFile()","res.attachment()","res.file()",0,"easy","res.download() prompts the browser to download the file, setting Content-Disposition to attachment."],

  // ===== HTML/CSS (expand 10→20) =====
  ["HTML/CSS","Which HTML attribute specifies an image's alternative text?","alt","src","title","description",0,"easy","The alt attribute provides alternative text for screen readers and displays when the image cannot be loaded."],
  ["HTML/CSS","What does CSS specificity determine?","Which style rule applies when multiple rules target the same element","The order of CSS file loading","The performance of CSS rendering","The inheritance level",0,"medium","Specificity is a weight calculated from selector types (inline > ID > class > element), determining which conflicting declaration wins."],
  ["HTML/CSS","Which CSS property creates space inside an element's border?","padding","margin","gap","spacing",0,"easy","Padding is the space between the content and the border. Margin is the space outside the border."],
  ["HTML/CSS","What is the box model in CSS?","A box wrapping every HTML element including content, padding, border, and margin","A CSS framework for layouts","A grid system","A flex container",0,"medium","The box model describes how every element is represented as a rectangular box with content, padding, border, and margin areas."],
  ["HTML/CSS","Which HTML element groups navigation links?","<nav>","<menu>","<sidebar>","<navigation>",0,"easy","The <nav> element semantically represents a section of navigation links, improving accessibility and SEO."],
  ["HTML/CSS","What does 'display: flex' do?","Creates a flex container for flexible layouts","Displays an element as a grid","Hides the element","Makes the element inline",0,"easy","Flexbox provides a flexible layout model enabling alignment, direction, ordering, and sizing of items within a container."],
  ["HTML/CSS","Which pseudo-class selects the first child of its parent?",":first-child",":first-of-type",":nth-child(1)","Both :first-child and :nth-child(1)",3,"medium",":first-child and :nth-child(1) both select an element that is the first child of its parent."],
  ["HTML/CSS","What is the purpose of a media query?","Applying CSS rules based on device characteristics like screen width","Querying database for media files","Defining responsive images","Controlling video playback",0,"easy","Media queries (@media) apply styles conditionally based on viewport size, resolution, orientation, or device capabilities."],
  ["HTML/CSS","Which HTML attribute opens a link in a new tab?","target=\"_blank\"","rel=\"new\"","href=\"_new\"","window=\"_blank\"",0,"easy","target=\"_blank\" tells the browser to open the linked page in a new tab or window."],
  ["HTML/CSS","What does 'position: absolute' do?","Positions an element relative to its nearest positioned ancestor","Positions relative to the viewport","Fixes the element on screen","Positions relative to its normal flow position",0,"medium","Absolute positioning removes the element from normal flow and positions it relative to the nearest ancestor with a non-static position."],

  // ===== SQL (expand 10→20) =====
  ["SQL","What does GROUP BY do?","Groups records that have the same values in specified columns","Orders records by a column","Filters groups with HAVING","Joins two tables",0,"medium","GROUP BY arranges identical data into groups, typically used with aggregate functions like COUNT, SUM, AVG."],
  ["SQL","Which JOIN returns all rows from the left table and matching rows from the right?","LEFT JOIN","RIGHT JOIN","INNER JOIN","FULL OUTER JOIN",0,"easy","LEFT JOIN returns all records from the left table, and matched records from the right. Unmatched right side values are NULL."],
  ["SQL","What is a foreign key?","A column that references a primary key in another table","A unique identifier for a record","An index on a column","A constraint for checking values",0,"medium","Foreign keys establish referential integrity between tables, ensuring values in the foreign key column exist in the referenced primary key column."],
  ["SQL","What does the LIKE operator do?","Pattern matching with % and _ wildcards","Comparison with exact values","Checking if a value is in a list","Matching regular expressions",0,"easy","LIKE performs pattern matching: % matches any sequence of characters, _ matches any single character."],
  ["SQL","Which function finds the highest value in a column?","MAX()","MIN()","TOP()","HIGHEST()",0,"easy","MAX() returns the maximum value in a given column."],
  ["SQL","What is a subquery?","A query nested inside another query","A query that runs after the main query","A query without a WHERE clause","A query that joins two tables",0,"medium","Subqueries are SELECT statements nested within another SQL statement, used in WHERE, HAVING, FROM, or SELECT clauses."],
  ["SQL","What does UNION do?","Combines result sets of multiple queries, removing duplicates","Combines two columns","Joins two tables","Creates a union of databases",0,"medium","UNION combines results from two or more SELECT statements, requiring the same number of columns and compatible data types."],
  ["SQL","What is the purpose of the HAVING clause?","Filtering groups after GROUP BY aggregation","Filtering rows before GROUP BY","Defining a join condition","Setting sort order",0,"medium","HAVING filters records from aggregate functions after GROUP BY, while WHERE filters rows before grouping."],
  ["SQL","Which statement modifies existing data in a table?","UPDATE","ALTER","MODIFY","CHANGE",0,"easy","UPDATE modifies existing records in a table, optionally filtered with WHERE."],
  ["SQL","What does a CASCADE delete do?","Deletes related records in child tables automatically","Deletes all records in the table","Deletes the table structure","Restores deleted records",0,"medium","ON DELETE CASCADE automatically deletes referencing rows in child tables when the referenced parent row is deleted."],

  // ===== MONGODB (expand 10→20) =====
  ["MongoDB","What is a replica set in MongoDB?","A group of MongoDB servers that maintain the same data set for redundancy","A copy of a collection","A backup of the entire database","A set of query replicas",0,"medium","A replica set provides high availability and data redundancy through automatic failover and data replication across multiple servers."],
  ["MongoDB","What does $set operator do in an update?","Sets the value of a field","Creates a new document","Sets the sort order","Sets the query filter",0,"easy","$set updates or creates a field with a specified value in matched documents."],
  ["MongoDB","How do you sort query results in MongoDB?",".sort({ field: 1 })",".orderBy({ field: 'asc' })",".arrange({ field: 1 })",".order({ field: 1 })",0,"medium","The sort() method specifies ascending (1) or descending (-1) order for query result documents."],
  ["MongoDB","What is a sharded cluster?","A horizontally partitioned database across multiple servers","A replicated database","A single-server database","A backup cluster",0,"hard","Sharding distributes data across multiple machines at the collection level, enabling horizontal scaling for large datasets."],
  ["MongoDB","Which operator checks if a field exists?","$exists","$has","$present","$defined",0,"easy","$exists: true selects documents that have the specified field (including null values)."],
  ["MongoDB","What is an embedded document in MongoDB?","A document nested inside another document","A separate document in another collection","A reference to another document","A subquery result",0,"medium","Embedded documents (subdocuments) are nested objects within a parent document, enabling denormalized data models."],
  ["MongoDB","What does the $lookup stage do in aggregation?","Performs a left outer join with another collection","Looks up a value in an array","Finds a document by ID","Searches text indexes",0,"medium","$lookup adds a new array field containing matching documents from another collection, similar to SQL JOINs."],
  ["MongoDB","What is the maximum document size in MongoDB?","16 MB","32 MB","64 MB","4 MB",0,"medium","MongoDB documents have a 16 MB size limit. For larger data, use GridFS which splits files into chunks."],
  ["MongoDB","Which index type supports text search?","text index","string index","search index","fulltext index",0,"medium","Text indexes support $text queries for searching string content with stemming, stop words, and scoring."],
  ["MongoDB","What is the aggregation pipeline?","A framework for data processing through sequential stages","A data backup pipeline","A replication mechanism","A connection pooling system",0,"easy","The aggregation pipeline passes documents through stages (like $match, $group, $sort) that transform and process data sequentially."],

  // ===== GIT & GITHUB (expand 10→20) =====
  ["Git & GitHub","What is a remote in Git?","A common repository hosted on a server that team members use","A cloud storage service","A local backup repository","A Git command shortcut",0,"medium","A remote is a version of the repository hosted on a server (like GitHub). git remote -v lists configured remotes."],
  ["Git & GitHub","What does 'git diff' show?","Changes between commits, working tree, or staging area","The difference between two branches","A visual diff of file contents","All of the above",3,"medium","git diff can compare working directory vs staging area, staging area vs last commit, or between any two commits/branches."],
  ["Git & GitHub","How do you undo the last commit while keeping changes?","git reset --soft HEAD~1","git revert HEAD","git checkout HEAD~1","git reset --hard HEAD~1",0,"medium","--soft reset moves HEAD back one commit but keeps changes staged. --hard discards everything."],
  ["Git & GitHub","What is a Git tag?","A reference pointing to a specific commit, often for releases","A label for branches","A metadata annotation","A commit message marker",0,"easy","Tags mark important commits (like v1.0.0). Lightweight tags are just pointers; annotated tags include metadata."],
  ["Git & GitHub","What does 'git merge --squash' do?","Combines all branch commits into one single commit on merge","Deletes the branch after merging","Squashes unrelated repositories","Squashes merge conflicts",0,"hard","Squash merge takes all commits from the feature branch and condenses them into a single commit on the target branch."],
  ["Git & GitHub","What is a .gitignore file?","Specifies intentionally untracked files to ignore","Contains Git configuration","Lists all ignored users","Stores Git credentials",0,"easy",".gitignore patterns tell Git which files (like node_modules, .env) to ignore and not track."],
  ["Git & GitHub","What does 'git stash' do?","Temporarily saves uncommitted changes","Permanently deletes changes","Stages all changes","Unstages changes",0,"medium","git stash saves local modifications so you can switch branches and reapply them later with git stash pop."],
  ["Git & GitHub","What is a fork on GitHub?","A personal copy of someone else's repository","A new branch created from the repository","A duplicate branch","A repository split",0,"easy","Forking creates a copy of a repository under your GitHub account, allowing independent development without affecting the original."],
  ["Git & GitHub","How do you resolve merge conflicts?","Manually edit conflicting files, stage, and commit","Delete the branch and start over","Git resolves them automatically","Run git fix to auto-resolve",0,"easy","Open conflicted files (marked with <<<<<<<), edit to resolve, stage with git add, then commit the merge."],
  ["Git & GitHub","What is Git rebase?","Reapplying commits on top of another base commit","Restoring deleted commits","Removing a branch","Rebuilding the repository",0,"hard","Rebase moves the entire feature branch to begin at the tip of the target branch, creating a linear history without merge commits."],

  // ===== DOCKER (expand 10→20) =====
  ["Docker","What is a Docker volume?","Persistent data storage outside the container's filesystem","A container backup","A Docker image layer","A container log file",0,"medium","Volumes are the preferred mechanism for persisting container data and sharing data between containers, managed by Docker."],
  ["Docker","What is the difference between CMD and ENTRYPOINT?","CMD provides defaults; ENTRYPOINT configures the container as executable","CMD runs first; ENTRYPOINT runs after","They are identical","CMD is required; ENTRYPOINT is optional",0,"medium","ENTRYPOINT defines the executable; CMD provides default arguments. Combined, they create flexible container images."],
  ["Docker","What does 'docker exec' do?","Runs a command in a running container","Starts a new container","Executes a Dockerfile","Builds an image",0,"easy","docker exec allows running additional processes inside an already-running container, commonly for debugging."],
  ["Docker","How do you view logs from a container?","docker logs <container>","docker view <container>","docker inspect <container>","docker events <container>",0,"easy","docker logs fetches the logs of a container's STDOUT and STDERR streams."],
  ["Docker","What is a multi-stage build?","Using multiple FROM statements to reduce image size","Building multiple images at once","Running multiple containers","Deploying to multiple environments",0,"hard","Multi-stage builds use multiple FROM statements in a Dockerfile, copying artifacts from intermediate stages to produce smaller final images."],
  ["Docker","What is the default networking mode for Docker containers?","bridge","host","none","overlay",0,"medium","The bridge network is the default, allowing containers to communicate through a private internal network on the host."],
  ["Docker","What does 'docker-compose up' do?","Creates and starts containers defined in docker-compose.yml","Checks for container updates","Stops running containers","Rebuilds all images",0,"easy","docker-compose up reads the compose file and creates/starts all defined services, networks, and volumes."],
  ["Docker","What is the purpose of .dockerignore?","Excludes files from the Docker build context","Ignores Docker errors","Disables Docker warnings","Configures Docker daemon",0,"easy","Similar to .gitignore, .dockerignore prevents unnecessary files from being sent to the Docker daemon during builds, improving speed."],
  ["Docker","How do you share data between containers?","Using shared volumes","Using environment variables","Using localhost networking","Using container IDs",0,"medium","Named volumes or bind mounts can be shared across multiple containers, enabling persistent data exchange."],
  ["Docker","What is Docker Swarm?","Docker's native container orchestration tool","A Docker image registry","A container runtime","A Docker networking plugin",0,"medium","Docker Swarm turns a pool of Docker hosts into a single virtual host for clustering and orchestration."],

  // ===== KUBERNETES (expand 10→20) =====
  ["Kubernetes","What is etcd in Kubernetes?","A distributed key-value store for cluster configuration data","A container runtime like Docker","A load balancer","A monitoring agent",0,"medium","etcd stores all cluster state and configuration reliably and consistently, serving as Kubernetes' database."],
  ["Kubernetes","What is a Namespace in Kubernetes?","A virtual cluster for isolating resources","A container namespace system","A Pod naming convention","A file system namespace",0,"easy","Namespaces provide isolated scopes for resources within a cluster, useful for multi-tenant environments."],
  ["Kubernetes","What is a PersistentVolume?","Storage provisioned by an administrator that Pods can consume","A temporary volume for Pods","A Docker volume managed by Kubernetes","An external storage service",0,"medium","PersistentVolumes are cluster-wide storage resources provisioned independently of Pods, with lifecycle decoupled from Pods."],
  ["Kubernetes","What does 'kubectl rollout undo' do?","Reverts a Deployment to a previous revision","Deletes a deployment","Cancels a rolling update","Restarts all Pods",0,"hard","Rollout undo reverts to the previous revision (or specified revision) of a Deployment, StatefulSet, or DaemonSet."],
  ["Kubernetes","What is a ConfigMap?","A non-confidential key-value configuration data object","A map of cluster configurations","A secret encryption key","A container configuration file",0,"easy","ConfigMaps store non-sensitive configuration data as key-value pairs that Pods can consume as environment variables or files."],
  ["Kubernetes","What is HorizontalPodAutoscaler?","Automatically scales Pod count based on resource usage","Scales cluster nodes horizontally","Scales vertical Pod resources","Manually scales Pods",0,"medium","HPA automatically adjusts the number of Pod replicas based on observed CPU/memory usage or custom metrics."],
  ["Kubernetes","What is a ResourceQuota?","Limits total resource consumption per Namespace","Limits per-Pod resources","A billing quota for cloud usage","A limit on cluster nodes",0,"medium","ResourceQuota enforces aggregate resource constraints (CPU, memory, storage, object count) within a Namespace."],
  ["Kubernetes","Which controller manages Pods through a ReplicaSet?","Deployment","DaemonSet","StatefulSet","Job",0,"easy","A Deployment manages a ReplicaSet, which in turn manages Pod replicas, providing declarative updates and rollbacks."],
  ["Kubernetes","What is a Readiness Probe?","Checks if a container is ready to accept traffic","Checks if a container is alive","Checks container resource usage","Probes the container's stored data",0,"medium","Readiness probes determine if a Pod is ready to serve traffic. If failed, the Pod is removed from Service endpoints."],
  ["Kubernetes","What is Helm in the Kubernetes ecosystem?","A package manager for Kubernetes applications","A container runtime","A monitoring tool","A CI/CD pipeline tool",0,"medium","Helm uses Charts (packaged Kubernetes resources) to define, install, and upgrade complex Kubernetes applications."],

  // ===== AWS (expand 10→20) =====
  ["AWS","What is AWS Lambda's maximum execution timeout?","15 minutes","5 minutes","30 minutes","1 hour",0,"medium","Lambda functions can run up to 15 minutes (900 seconds). For longer processes, use services like ECS or Step Functions."],
  ["AWS","Which service provides object-level storage for backups and archives?","Amazon S3 Glacier","Amazon EBS","Amazon EFS","Amazon Instance Store",0,"easy","S3 Glacier is a low-cost storage service designed for data archiving and long-term backup with retrieval times from minutes to hours."],
  ["AWS","What does ELB stand for?","Elastic Load Balancing","Extreme Load Balancing","Elastic Load Balancer","Extended Load Balancing",0,"easy","ELB automatically distributes incoming traffic across multiple targets like EC2 instances, containers, and IP addresses."],
  ["AWS","Which service provides a fully managed message queue?","Amazon SQS","Amazon SNS","Amazon Kinesis","Amazon MQ",0,"medium","SQS (Simple Queue Service) offers fully managed message queues for decoupling microservices and distributed systems."],
  ["AWS","What is an AWS Availability Zone?","A distinct location within an AWS Region with isolated infrastructure","An entire AWS geographic region","A content delivery edge location","A VPC subnet",0,"easy","Availability Zones are physically separate data centers within a Region, each with independent power, cooling, and networking."],
  ["AWS","Which service monitors AWS resources and sends alerts?","Amazon CloudWatch","AWS Config","AWS CloudTrail","Amazon Inspector",0,"medium","CloudWatch monitors metrics, collects logs, and can trigger alarms and automated actions based on defined thresholds."],
  ["AWS","What is the shared responsibility model?","AWS secures the cloud infrastructure; customers secure their data and applications","AWS is responsible for everything","Customers are responsible for everything","Security is shared 50/50",0,"medium","AWS manages the security of the cloud (physical infrastructure, hardware), while customers manage security IN the cloud (data, configurations, IAM)."],
  ["AWS","What is an AMI?","Amazon Machine Image, a template for creating EC2 instances","Amazon Managed Instance","Amazon Memory Image","Automated Machine Interface",0,"easy","AMIs are pre-configured templates containing OS, software, and configurations used to launch EC2 instances."],
  ["AWS","Which service distributes incoming traffic to multiple targets in multiple Availability Zones?","ELB (Elastic Load Balancing)","Route 53","CloudFront","Auto Scaling",0,"easy","ELB spreads traffic across instances in multiple AZs for fault tolerance and high availability."],
  ["AWS","What is AWS Organizations?","A service to centrally manage multiple AWS accounts","A tool for organizing EC2 instances","A resource tagging system","A project management tool",0,"medium","AWS Organizations lets you consolidate multiple AWS accounts into an organization, centrally managing policies and billing."],

  // ===== ANDROID DEVELOPMENT (KOTLIN) (expand 10→20) =====
  ["Android Development (Kotlin)","What is an Activity in Android?","A single focused screen with a user interface","A background service","A content provider","A broadcast receiver",0,"easy","Activities are the entry point for interacting with users. Each Activity represents one screen with a UI."],
  ["Android Development (Kotlin)","What is the purpose of a Fragment?","A reusable portion of the UI within an Activity","A complete screen replacement","A background task","A data storage unit",0,"medium","Fragments represent modular sections of an Activity's UI, with their own lifecycle and input handling."],
  ["Android Development (Kotlin)","What does the 'lateinit' modifier allow?","Deferred initialization of non-null properties","Late binding of methods","Lazy property initialization","Nullable property",0,"medium","lateinit allows declaring a non-null property without initializing it at declaration, initializing it later before use."],
  ["Android Development (Kotlin)","What is a ContentProvider?","Manages access to a structured set of app data","Provides content for the UI","A web content downloader","A file system access API",0,"medium","ContentProviders encapsulate data and provide it to other applications through a standard interface."],
  ["Android Development (Kotlin)","What is a Service in Android?","A component for long-running background operations","A web service client","A UI component","A data access layer",0,"medium","Services run in the background indefinitely, performing operations like network calls or music playback without a UI."],
  ["Android Development (Kotlin)","What does 'Sealed Class' mean in Kotlin?","A class that restricts the class hierarchy to a fixed set of types","A class that cannot be extended","A class with private constructor","A final class",0,"hard","Sealed classes define a restricted hierarchy: all subclasses are known at compile time, making exhaustive when expressions possible."],
  ["Android Development (Kotlin)","What is Data Binding in Android?","Binds UI components to data sources declaratively","Binds network requests","Binds databases","Binds services to activities",0,"medium","Data Binding Library generates binding classes to connect layout variables and expressions directly to UI components."],
  ["Android Development (Kotlin)","What is a BroadcastReceiver?","Listens for system-wide broadcast announcements","Receives internet broadcasts","Captures radio signals","Records audio broadcasts",0,"medium","BroadcastReceivers respond to system-wide events (like battery low, SMS received) across the entire device."],
  ["Android Development (Kotlin)","What is the 'elvis operator' in Kotlin (?:)?","Returns the left side if non-null, otherwise the right side","A ternary operator replacement","Checks for null and throws exception","Returns null if either value is null",0,"easy","The elvis operator provides a default value when a nullable expression is null: val len = str?.length ?: 0."],
  ["Android Development (Kotlin)","What is a WorkManager used for?","Scheduling deferrable, guaranteed background work","Managing worker threads","Managing payroll workers","Managing UI workers",0,"medium","WorkManager schedules and runs deferrable background tasks that need guaranteed execution, even if the app exits."],

  // ===== iOS DEVELOPMENT (SWIFT) (expand 10→20) =====
  ["iOS Development (Swift)","What is a 'guard' statement in Swift?","Exits a scope early if condition is false, requiring else","A conditional statement like if","A loop guard","A security feature",0,"medium","guard let or guard else requires an else clause that must exit the scope (return, break, throw), ensuring early exit on failure."],
  ["iOS Development (Swift)","What is a ViewController in iOS?","Manages a view hierarchy and responds to user interactions","Controls the app's data model","Manages network connections","Configures app preferences",0,"easy","UIViewController manages views, handles events, and coordinates with model data in the MVC pattern."],
  ["iOS Development (Swift)","What is Codable in Swift?","A type alias for Encodable & Decodable protocols","A coding style guide","A debugging tool","A code signing mechanism",0,"medium","Codable combines Encodable and Decodable, enabling easy serialization/deserialization between Swift types and external formats like JSON."],
  ["iOS Development (Swift)","What is Auto Layout?","A constraint-based layout system for responsive interfaces","Automatic screen rotation","A layout animation framework","A grid layout system",0,"easy","Auto Layout defines rules (constraints) for view positions and sizes, adapting to different screen sizes and orientations."],
  ["iOS Development (Swift)","What is an enum with associated values?","An enum case that stores additional typed data","An enum with numeric values","A struct-like enum","A protocol conforming enum",0,"hard","Associated values allow enum cases to store custom data of any type: enum Result { case success(Data); case failure(Error) }."],
  ["iOS Development (Swift)","What is a 'deinit' in Swift?","Called when an instance is deallocated","The initialization method","A destructive operator","A debugging method",0,"medium","Deinitializers (deinit) are called automatically before a class instance is deallocated, used for cleanup."],
  ["iOS Development (Swift)","What is Core Data?","A framework for managing object graphs and persistence","A database query language","A networking framework","A UI component library",0,"medium","Core Data provides object graph management and persistence, managing the lifecycle of model objects and their relationships."],
  ["iOS Development (Swift)","What is a computed property?","A property that calculates its value each time it's accessed","A property stored in the database","A property with a fixed value","A read-only property",0,"medium","Computed properties don't store a value; they provide a getter (and optional setter) that computes the value dynamically."],
  ["iOS Development (Swift)","What is the 'defer' keyword used for?","Executes a block of code just before scope exit","Defers function execution","Delays variable assignment","Pauses thread execution",0,"hard","defer schedules a block to execute when the current scope is exited, useful for cleanup regardless of how the scope exits (return, throw)."],
  ["iOS Development (Swift)","What is an Extension in Swift?","Adds new functionality to an existing type","Extends a class through inheritance","Extends the app's memory","Extends code execution time",0,"easy","Extensions add computed properties, methods, initializers, and protocol conformance to existing types."],

  // ===== MACHINE LEARNING (expand 10→20) =====
  ["Machine Learning","What is a Confusion Matrix?","A table describing classification model performance","A matrix of confusing data points","A correlation matrix","An identity matrix",0,"medium","A confusion matrix tabulates true positive, true negative, false positive, and false negative predictions for classifier evaluation."],
  ["Machine Learning","What is the difference between Bagging and Boosting?","Bagging trains models in parallel; Boosting trains sequentially correcting errors","Bagging is faster; Boosting is more accurate","There's no difference","Bagging is for regression; Boosting is for classification",0,"hard","Bagging (Random Forest) trains models independently and averages. Boosting (XGBoost) trains sequentially, each model learning from previous errors."],
  ["Machine Learning","What does PCA (Principal Component Analysis) do?","Reduces dimensionality by finding orthogonal axes of maximum variance","Performs classification","Clusters data points","Normalizes features",0,"medium","PCA transforms features into uncorrelated principal components ordered by variance, used for dimensionality reduction and noise filtering."],
  ["Machine Learning","What is regularization in ML?","Techniques to prevent overfitting by penalizing model complexity","A data normalization method","A feature selection approach","A training loop scheduling",0,"medium","Regularization (L1/Lasso, L2/Ridge) adds a penalty term to the loss function, discouraging overly complex models."],
  ["Machine Learning","What is the difference between Precision and Recall?","Precision = TP/(TP+FP); Recall = TP/(TP+FN)","Precision = accuracy; Recall = F1","They are identical","Precision = FP rate; Recall = FN rate",0,"medium","Precision measures how many positive identifications were correct. Recall measures how many actual positives were identified correctly."],
  ["Machine Learning","What is a Decision Tree?","A tree-like model of decisions and their consequences","A random forest simplified","A deep learning architecture","A clustering algorithm",0,"easy","Decision trees split data based on feature values into leaf nodes representing decisions, interpretable and handling both numerical and categorical data."],
  ["Machine Learning","What does 'One-Hot Encoding' do?","Converts categorical variables into binary columns","Encodes data with a single bit","Creates a single encoding for all features","Merges multiple features into one",0,"medium","One-hot encoding creates binary columns for each category value, avoiding the ordinal assumption of label encoding."],
  ["Machine Learning","What is Transfer Learning?","Using a pre-trained model on a new but related task","Transferring data between servers","Moving model weights to production","Learning from transferred knowledge",0,"medium","Transfer learning leverages knowledge from a model trained on one task as a starting point for a related task, saving training time and data."],
  ["Machine Learning","What is the bias-variance tradeoff?","Balancing underfitting (bias) and overfitting (variance)","Balancing training speed and accuracy","Balancing model size and memory","Balancing data size and model complexity",0,"medium","High bias underfits (oversimplified); high variance overfits (memorizes noise). Optimal model balances both."],
  ["Machine Learning","What is t-SNE used for?","Dimensionality reduction for visualization of high-dimensional data","Time series forecasting","Text classification","Image segmentation",0,"hard","t-SNE maps high-dimensional data to 2D or 3D for visualization, preserving local structure and revealing clusters."],
];

// Skills that need 10 NEW questions (existing skills being expanded from 10→20)
const existingSkillsNeedingExpansion = [
  "Python","Java","C++","JavaScript","React","C","C#","TypeScript","Node.js","Express.js",
  "HTML/CSS","SQL","MongoDB","Git & GitHub","Docker","Kubernetes","AWS",
  "Android Development (Kotlin)","iOS Development (Swift)","Machine Learning"
];

// Skills in NEW that are already covered in existing
const coveredInExpansion = new Set(existingSkillsNeedingExpansion);

// Read existing questions
let existingQuestions = [];
try {
  const raw = fs.readFileSync(path.join(__dirname, 'questions.json'), 'utf8');
  existingQuestions = JSON.parse(raw);
  console.log(`Read ${existingQuestions.length} existing questions.`);
} catch(e) {
  console.error('Could not read existing:', e.message);
  existingQuestions = [];
}

// Build the complete list: existing + new for expansion + new for missing skills
const result = [...existingQuestions];

// Add NEW questions
for (const q of NEW) {
  result.push({
    skill: q[0],
    question: q[1],
    options: [q[2], q[3], q[4], q[5]],
    correctAnswer: q[6],
    difficulty: q[7],
    explanation: q[8]
  });
}

// Count per skill
const countPerSkill = {};
for (const q of result) {
  if (!countPerSkill[q.skill]) countPerSkill[q.skill] = 0;
  countPerSkill[q.skill]++;
}

console.log(`\nTotal questions: ${result.length}`);
console.log(`Total skills: ${Object.keys(countPerSkill).length}`);
for (const [skill, count] of Object.entries(countPerSkill).sort()) {
  const status = count >= 20 ? '✓' : count >= 10 ? '○' : '✗';
  console.log(`  ${status} ${skill}: ${count}`);
}

fs.writeFileSync(path.join(__dirname, 'questions_new.json'), JSON.stringify(result, null, 2));
console.log('\nWritten to questions_new.json');
